  # Find all the available rules by running:
  # swiftlint rules
  
  #included: # paths to include during linting. `--path` is ignored if present.
#  - Source

disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - shorthand_operator
  - empty_enum_arguments
  - force_cast
  - large_tuple
  - trailing_whitespace
  - redundant_string_enum_value
  - multiple_closures_with_trailing_closure
  - unused_setter_value
  - syntactic_sugar
  - implicit_getter

cyclomatic_complexity:
  warning: 40 # two nested ifs are acceptable
  error: 50   # six nested ifs shows warning, 6 causes compile error

function_parameter_count : 11

opt_in_rules: # some rules are only opt-in
  # - empty_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - AppFolder\ App/Class/*
 # - AppFolder\ App/ViewController/* //Enabled for this

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# binary rules can set their severity level
# force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

# rules that have both warning and error levels, can set just the warning level
# implicitly

line_length: 400
# they can set both implicitly with an array

type_body_length:
  - 600 # warning
  - 800 # error
# or they can set both explicitly

file_length:
  warning: 1000
  error: 2500

function_body_length:
  - 400 #warning
  - 800 #error

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

identifier_name:
  allowed_symbols: "_"
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
    

excluded:
  - Pods
  - ./*/Core
  - Tests
  - .build
  - */AppStringResources.swift
  
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)


#Add below script to run swiftlint
# if which swiftlint >/dev/null; then
#  swiftlint
#else
#  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
#fi
